src/main/java/com/lowes/entity/Usuario.java
package com.lowes.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * @author Josue Sanchez
 */

@Entity
@Table(name = "USUARIO", schema = "LWS584")
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idUsuario;
	private Compania compania;
	private Locacion locacion;
	private Perfil perfil;
	private Puesto puesto;
	private Usuario usuarioJefe;
	private int numeroEmpleado;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String correoElectronico;
	private String cuenta;
	private String contrasena;
	private short activo;
	private Date creacionFecha;
	private Integer creacionUsuario;
	private Integer modificacionUsuario;
	private Date modificacionFecha;
	private short esSolicitante;
	private short esFiguraContable;
	private short esAutorizador;
	private short especificaSolicitante;
	private short esBeneficiarioCajaChica;
	private String fotoPerfil;
	private Integer numeroProveedor;
	private String rfc;
	
	/*Ids de objetos*/
	
	private int idCompania;
	private int idLocacion;
	private int idPerfil;
	private int idPuesto;
	private int idUsuarioJefe;

	private String nombreCompletoUsuario;
	private String numeroNombreCompletoUsuario;
	
	private Boolean esSolicitanteB;
	private Boolean esFiguraContableB;
	private Boolean esAutorizadorB;
	private Boolean especificaSolicitanteB;
	private Boolean esBeneficiarioCajaChicaB;
	
	private Boolean tieneFotoPerfil; 
	
	public Usuario() {
	}
	
	public Usuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario(int idUsuario, Compania compania, Locacion locacion, Perfil perfil, Puesto puesto,
			int numeroEmpleado, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico,
			String cuenta, String contrasena, short activo, Date creacionFecha, int creacionUsuario,
			short esSolicitante, short esFiguraContable, short esAutorizador, short especificaSolicitante,
			short esBeneficiarioCajaChica,String fotoPerfil, Integer numeroProveedor, String rfc) {
		this.idUsuario = idUsuario;
		this.compania = compania;
		this.locacion = locacion;
		this.perfil = perfil;
		this.puesto = puesto;
		this.numeroEmpleado = numeroEmpleado;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correoElectronico = correoElectronico;
		this.cuenta = cuenta;
		this.contrasena = contrasena;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.esSolicitante = esSolicitante;
		this.esFiguraContable = esFiguraContable;
		this.esAutorizador = esAutorizador;
		this.especificaSolicitante = especificaSolicitante;
		this.esBeneficiarioCajaChica = esBeneficiarioCajaChica;
		this.fotoPerfil = fotoPerfil;
		this.numeroProveedor = numeroProveedor;
		this.rfc = rfc;
	}

	public Usuario(int idUsuario, Compania compania, Locacion locacion, Perfil perfil, Puesto puesto, Usuario usuarioJefe,
			int numeroEmpleado, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico,
			String cuenta, String contrasena, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario, short esSolicitante, short esFiguraContable,
			short esAutorizador, short especificaSolicitante, short esBeneficiarioCajaChica,String fotoPerfil, Integer numeroProveedor, String rfc) {
		this.idUsuario = idUsuario;
		this.compania = compania;
		this.locacion = locacion;
		this.perfil = perfil;
		this.puesto = puesto;
		this.usuarioJefe = usuarioJefe;
		this.numeroEmpleado = numeroEmpleado;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correoElectronico = correoElectronico;
		this.cuenta = cuenta;
		this.contrasena = contrasena;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.esSolicitante = esSolicitante;
		this.esFiguraContable = esFiguraContable;
		this.esAutorizador = esAutorizador;
		this.especificaSolicitante = especificaSolicitante;
		this.esBeneficiarioCajaChica = esBeneficiarioCajaChica;
		this.fotoPerfil = fotoPerfil;
		this.numeroProveedor = numeroProveedor;
		this.rfc = rfc;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_USUARIO", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_CAMPANIA", nullable = false)
	public Compania getCompania() {
		return this.compania;
	}

	public void setCompania(Compania compania) {
		this.compania = compania;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_LOCACION", nullable = false)
	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_PERFIL", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_PUESTO", nullable = false)
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO_JEFE")
	public Usuario getUsuario() {
		return this.usuarioJefe;
	}

	public void setUsuario(Usuario usuarioJefe) {
		this.usuarioJefe = usuarioJefe;
	}
	

	@Column(name = "NUMERO_EMPLEADO", nullable = false)
	public int getNumeroEmpleado() {
		return this.numeroEmpleado;
	}

	public void setNumeroEmpleado(int numeroEmpleado) {
		this.numeroEmpleado = numeroEmpleado;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO_PATERNO", nullable = false, length = 30)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "APELLIDO_MATERNO", nullable = false, length = 30)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "CORREO_ELECTRONICO", nullable = false, length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "CUENTA", nullable = false, length = 50)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "CONTRASENA", nullable = false, length = 100)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}
    
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA")
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO", length = 26)
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "ES_SOLICITANTE", nullable = false)
	public short getEsSolicitante() {
		return this.esSolicitante;
	}

	public void setEsSolicitante(short esSolicitante) {
		this.esSolicitante = esSolicitante;
	}

	@Column(name = "ES_FIGURA_CONTABLE", nullable = false)
	public short getEsFiguraContable() {
		return this.esFiguraContable;
	}

	public void setEsFiguraContable(short esFiguraContable) {
		this.esFiguraContable = esFiguraContable;
	}

	@Column(name = "ES_AUTORIZADOR", nullable = false)
	public short getEsAutorizador() {
		return this.esAutorizador;
	}

	public void setEsAutorizador(short esAutorizador) {
		this.esAutorizador = esAutorizador;
	}

	@Column(name = "ESPECIFICA_SOLICITANTE", nullable = false)
	public short getEspecificaSolicitante() {
		return this.especificaSolicitante;
	}

	public void setEspecificaSolicitante(short especificaSolicitante) {
		this.especificaSolicitante = especificaSolicitante;
	}
	

src/main/java/com/lowes/controller/MenuController.java
package com.lowes.controller;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.lowes.entity.Menu;
import com.lowes.service.MenuService;

/**
 * @author Josue Sanchez
 * @version 1.0
 */

@Controller
@PreAuthorize("hasRole('ROLE_USER')")
public class MenuController {

	
	public MenuController(){
		System.out.println("MenuController");
	}
	
	@Autowired
	private MenuService menuService;
	
	
	// metodo ajax para la carga dinamica de edicion.
	@RequestMapping(value = "/createMenu", method = RequestMethod.GET, produces = "text/html; charset=utf-8")
	public @ResponseBody ResponseEntity<String> createMenu(HttpSession session, 
			HttpServletRequest request, HttpServletResponse response) {

		StringBuilder html = new StringBuilder();
		// extraer menu de la tabla
		List<Menu> lstMenu =  menuService.getAllMenu();
		
		// prevent null y vacios
		if(lstMenu != null && lstMenu.isEmpty() == false){
			
			//extraer todos los nodos padre
			List<Menu> lstNodosPadre = new ArrayList<>();
			for(Menu lst : lstMenu){
		       if(lst.getEsNodo() == 0){
		    	   lstNodosPadre.add(lst);
		       }		
			}
			
			
			if(lstNodosPadre.size() > 0){
				for(Menu lstNPadre : lstNodosPadre){
					html.append("<ul>");
					 html.append("<li>");
					   html.append("<input class=\"check\" id=\""+lstNPadre.getIdMenu()+"\" type=\"checkbox\"><span>"+lstNPadre.getNombre()+"</span>");
					     List<Menu> hijos = getHijos(lstNPadre.getIdMenu(),lstMenu);
					     if(hijos != null && hijos.isEmpty() == false){
					    	   for(Menu h : hijos){
						    	 html.append("<ul>");
										 html.append("<li>");
										   html.append("<input class=\"check\" id=\""+h.getIdMenu()+"\" type=\"checkbox\"><span>"+h.getNombre()+"</span>");
										   List<Menu> nietos = getHijos(h.getIdMenu(),lstMenu);
										   if(nietos != null && nietos.isEmpty() == false){
										    	 html.append("<ul>");
										    	    for(Menu n : nietos){
										    	    	html.append("<li><input class=\"check\"  id=\""+n.getIdMenu()+"\" type=\"checkbox\"><span>"+n.getNombre()+"</span></li>");
										    	    }
										    	 html.append("</ul>");
										   }
										 html.append("</li>");
						    	 html.append("</ul>");
					    	  }
					     }
					 html.append("</li>");
					html.append("</ul>");
				}
			}
			
			
		}
		

		HttpHeaders responseHeaders = new HttpHeaders();
		responseHeaders.add("Content-Type", "text/html; charset=utf-8");
		return new ResponseEntity<String>(html.toString(), responseHeaders, HttpStatus.CREATED);
	}
	
	// metodo ajax para la carga dinamica de edicion.
		@RequestMapping(value = "/createSideMenu", method = RequestMethod.GET, produces = "text/html; charset=utf-8")
		public @ResponseBody ResponseEntity<String> createMenuLateral(HttpSession session, 
				HttpServletRequest request, HttpServletResponse response) {
			
			
			StringBuilder menu = new StringBuilder();
			
	    menu.append("<li class=\"\">");
			  menu.append("<a href=\"#\"><i class=\"fa fa-sitemap fa-fw\"></i>").append("Multi-Level Dropdown").append("<span class=\"fa arrow\"></span></a>");
			  
			  menu.append("<ul class=\"nav nav-second-level collapse\" aria-expanded=\"false\" style=\"height: 0px;\">");
			     menu.append("<li><a href=\"#\">Second Level Item</a></li>");
			     menu.append("<li class=\"\">");
			     menu.append("<a href=\"#\">Third Level <span class=\"fa arrow\"></span></a>");
			      menu.append("<ul class=\"nav nav-third-level collapse\" aria-expanded=\"false\" style=\"height: 0px;\">");
			        menu.append("<li><a href=\"#\">Third Level Item</a></li>");
			      menu.append("</ul>");
                 //   <!-- /.nav-third-level -->
			     menu.append("</li>");
			  menu.append("</ul>");
            //<!-- /.nav-second-level -->
		menu.append("</li>");

		HttpHeaders responseHeaders = new HttpHeaders();
		responseHeaders.add("Content-Type", "text/html; charset=utf-8");
		return new ResponseEntity<String>(menu.toString(), responseHeaders, HttpStatus.CREATED);
		}
	
	
	
	
	
	private List<Menu> getHijos(Integer id, List<Menu> setMenu){
		
		List<Menu> childrenAux = new ArrayList<>();
		
		for(Menu menu : setMenu){
			if(menu.getMenuPadre() != null && menu.getMenuPadre().getIdMenu() == id){
				childrenAux.add(menu);
			}
		}
		return childrenAux;
	}
	
	
	
}

src/main/webapp/WEB-INF/pages/template/menu.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ page import="com.lowes.util.Etiquetas"%>
<%
	Etiquetas etiqueta = new Etiquetas("es");
%>
<!-- <span class="label label-primary">Personal</span>
 -->


<div id="usuario_logged">
	<div class="center_login_img">
	
	<c:choose>
    <c:when test="${model.usuario.fotoPerfil eq 'default.png'}">
         <img class="circular" src="${pageContext.request.contextPath}/resources/images/${model.usuario.fotoPerfil}" onContextMenu="return false;" />
    </c:when>
    <c:otherwise>
         <img class="circular" src="${pageContext.request.contextPath}/archivos/pp/${model.usuario.fotoPerfil}" onContextMenu="return false;" />
    </c:otherwise>
</c:choose>

		
	</div>
	   <div class="center_login">
      <h4>${model.usuario.nombre}  ${model.usuario.apellidoPaterno}  ${model.usuario.apellidoMaterno}</h4>
      <span class="label label-success">${model.usuario.perfil.descripcion}</span>
	</div>
	
	
<%-- 	<div class="row">
		<div class="col-md-6"><span class="label label-warning">${model.usuario.locacion.descripcion}</span></div>
	</div> --%>
</div>

<ul class="nav collapse" id="side-menu">
	<li><a href="<%=request.getContextPath()%>/"><i class="fa fa-dashboard fa-fw"></i>
			<%=etiqueta.DASHBOARD%></a></li>
	<c:forEach items="${model.menuList}" var="menuPadre">
		<li><a><i class="fa ${menuPadre.classIcon} fa-fw"></i> ${menuPadre.nombre}
				<span class="fa arrow"></span> </a>
			<ul class="nav nav-second-level">
				<c:forEach items="${menuPadre.menus}" var="menuPrimerHijo">
					<li><c:choose>
							<c:when test="${fn:length(menuPrimerHijo.menus) == 0}">
								<a href="${menuPrimerHijo.ruta}"><i
									class="nav nav-second-level"></i> ${menuPrimerHijo.nombre} </a>
							</c:when>
							<c:otherwise>
								<a><i class="fa ${menuPrimerHijo.classIcon} fa-fw"></i>
									${menuPrimerHijo.nombre} <span class="fa arrow"></span> </a>
								<ul class="nav nav-third-level">
									<c:forEach items="${menuPrimerHijo.menus}"
										var="menuSegundoHijo">
										<li><a href="${menuSegundoHijo.ruta}"> <i
												class="nav nav-third-level"> </i> ${menuSegundoHijo.nombre}
										</a></li>
									</c:forEach>
								</ul>
							</c:otherwise>
						</c:choose></li>
				</c:forEach>
			</ul></li>
	</c:forEach>
</ul>

src/main/webapp/WEB-INF/pages/template/nav_superior.jsp
<!-- Navigation -->
<div id="wrapper" class="toggled">
	<nav class="navbar navbar-default navbar-static-top" role="navigation"
		style="margin-bottom: 0">


		<!--<div style="width: 225px;" class="menu-box">
			 <img src="${pageContext.request.contextPath}/resources/images/adcontent.png" /> 
		</div>-->

		<div
			style="width: 225px;  padding-top: 15px; margin-right: 21px;"
			class="menu-box">

 <a onClick="menuRaw()" href="#" class="btn btn-default btn-md hide-menu"> <span
				class="	glyphicon glyphicon-transfer"></span> Esconder menu
			</a>
			<a href="logout" class="btn btn-default btn-md"> <span
				class="glyphicon glyphicon-log-out"></span> Salir
			</a> 
			
			<div style="font-size:9px; position:relative; margin:10px 20px 0 0; right:-10px; float:right; color:#FFFFFF"> DM-2.8 </div>

		</div>





		<div style="width: 149px; float: left; margin-left: 53px;"
			class="menu-box">
			<a href="."><img
				src="${pageContext.request.contextPath}/resources/images/lowes.png" />
				</a>

		</div>



		<div id="sidebarmenu1" class="navbar-default sidebar" role="navigation">
			<div class="sidebar-nav navbar-collapse">
				<jsp:include page="menu.jsp" />

			</div>
			<!-- /.sidebar-collapse -->
		</div>
		<!-- /.navbar-static-side -->
	</nav>
</div>